# Generated by Django 3.0.4 on 2020-05-02 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_movie_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='trailer_link',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
